addons:
    apt:
        packages:
            - cmake
            - g++
            - swig
            - pkg-config
            - libfftw3-dev
            - libboost-all-dev
            - libcppunit-dev
            - libgsl0-dev
            - libusb-dev
            - libsdl1.2-dev
            - libxi-dev
            - libqt4-opengl-dev
            - libqwt-dev
            - libfontconfig1-dev
            - libxrender-dev
            - python-dev
            - python-wxgtk2.8
            - python-numpy
            - python-cheetah
            - python-lxml
            - python-sip
            - python-sip-dev
            - doxygen

language: cpp

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required

script:
    # Why does this not work?
    #- git submodule update --init --recursive
    - git clone https://github.com/gnuradio/volk
    - python test_cheetah.py
    - mkdir build/ && cd build/
    - cmake ..
    - make
    - ctest
    - make install

notifications:
    email: false
